language: php
php:
  - 5.4
  - 5.5
  - 5.6
addons:
  code_climate:
    repo_token: be1e1f80ab2747d98df9186da66baaf17878c89e331fa030c60b95afc13cb75d
before_script: composer install
script: phpunit --configuration tests/phpunit.xml tests
after_script:
  - vendor/bin/test-reporter