language: php
php:
  - 5.5
  - 5.6
  - 7.0
addons:
  code_climate:
    repo_token: 80e7a148d0128e19f6483da43526d78f4430c60a201d141734a386ab189e052e
before_script:
  - sed -i '/phpdocumentor/d' composer.json
  - composer install
script:
  - phpunit --configuration test/phpunit.xml test
  - ./vendor/bin/phpcs --ignore=*/vendor/*,*/bin/* --standard=./vendor/athens/standard/ruleset.xml .
after_script:
  - vendor/bin/test-reporter