language: php
php:
  - 5.5
  - 5.6
  - 7.0
addons:
  code_climate:
    repo_token: be1e1f80ab2747d98df9186da66baaf17878c89e331fa030c60b95afc13cb75d
before_script:
  - sed -i '/phpdocumentor/d' composer.json
  - composer install
script:
  - phpunit --configuration tests/phpunit.xml tests
  - ./vendor/bin/phpcs --ignore=*/vendor/*,*/bin/* --standard=./vendor/uwdoem/standard/ruleset.xml .
after_script:
  - vendor/bin/test-reporter